# Generated by Django 4.1 on 2022-08-28 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_videogames_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogames',
            name='name',
        ),
        migrations.RemoveField(
            model_name='videogames',
            name='published_year',
        ),
    ]
