# Generated by Django 4.1 on 2022-08-28 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_videogames_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videogames',
            options={},
        ),
    ]
