# Generated by Django 4.1 on 2022-08-28 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_videogames_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videogames',
            options={'ordering': (('name', 'published_year'),)},
        ),
    ]
