# Generated by Django 4.1 on 2022-08-28 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_videogames_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogames',
            name='modified',
        ),
    ]
