# Generated by Django 4.1 on 2022-08-28 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_genres_options_alter_platform_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genres',
            options={'ordering': ('geName',)},
        ),
        migrations.RenameField(
            model_name='genres',
            old_name='name',
            new_name='geName',
        ),
    ]
