# Generated by Django 4.1 on 2022-08-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_genres_options_remove_genres_gename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='name',
            field=models.CharField(default='Aventura', max_length=30),
        ),
    ]
