# Generated by Django 4.1 on 2022-08-28 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_genres_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genres',
            options={'ordering': ['name']},
        ),
    ]
