# Generated by Django 4.1 on 2022-08-29 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_genres_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genres',
            name='modified',
        ),
    ]
